tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "git"
brew "git-delta"
brew "mas"
brew "n"
brew "neovim"
brew "openssl@3"
brew "peco"
brew "readline"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "sqlite"
brew "tcl-tk"
brew "tig"
brew "tmux"
brew "tree"
brew "xz"
brew "zlib"
brew "zsh"
cask "1password"
cask "alfred"
cask "blackhole-16ch"
cask "blackhole-2ch"
cask "brave-browser"
cask "clipy"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-ricty-diminished"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "krisp"
cask "obs"
cask "slack"
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
