# カラーをhybridに変更
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vim-hybrid.vim'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/lightline.vim'

# 自動補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# インクリメンタルサーチ
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/denite.vim'

# deniteの補助プラグイン
[[plugins]]
repo = 'Shougo/neomru.vim'
depends = 'denite.nvim'
on_path = '.*'

# deniteの補助プラグイン
[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'
on_event = 'TextYankPost'

# バッファ上のコードを実行する
# Ex) :QuickRun ruby
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

# カーソル位置のコンテキストにあわせてFiletypeを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのFiletypeを判定する
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# インデントを可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
'''

# 末尾の無駄なスペースをハイライト／削除する
# :FixWhitespace で削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# カッコの終端を自動入力
[[plugins]]
repo = 'Townk/vim-autoclose'

# 構文エラーを表示
[[plugins]]
repo =  'scrooloose/syntastic'

# 検索したときにマッチ数や順番を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vim-anzu.vim'

# 日本語ドキュメントを表示
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
  set helplang=ja,en
'''

# VSCodeのようなエディタ機能を実現
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
