# カーソル位置のコンテキストにあわせてFiletypeを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのFiletypeを判定する
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# インデントを可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
'''

# 末尾の無駄なスペースをハイライト／削除する
# :FixWhitespace で削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# カッコの終端を自動入力
[[plugins]]
repo = 'Townk/vim-autoclose'

# 構文エラーを表示
[[plugins]]
repo =  'scrooloose/syntastic'

# 検索したときにマッチ数や順番を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/vim-anzu.vim'

# 日本語ドキュメントを表示
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
  set helplang=ja,en
'''

# ----------------
# シンタックスハイライト
[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'leafgarland/typescript-vim'


[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'


[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'
# ----------------
